### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by danielvmnztr** [fleekxyz/fleekxyz-support#1]
I'm facing _Error: File with path "hello.txt" not found._

![image_2023-01-19_20-37-00](https://user-images.githubusercontent.com/47860314/213480206-0be9e3a5-a546-4a4d-83da-83443138242d.png)

**Comment by danielvmnztr** [comment]
Ouh, got it
https://ipfs.io/ipfs/QmS2AAiwtbRgN3s4pXh3iXDkLHCKbCceCsmoeYEfZTjxvx

**Comment by riveign** [comment]
@danielvmnztr Fantastic that you got it! Would you mind pointing out what was the problem and how you fixed it?

**Comment by danielvmnztr** [comment]
> @danielvmnztr Fantastic that you got it! Would you mind pointing out what was the problem and how you fixed it?

Actually I'm not an expert, but I investigated the error message I got that the file hello.txt was not found, then I tried to create the file and place it in my home directory. and, yes finally the problem is solved. a very exciting experience to be able to try this, I want to explore more in the future later. 👏🏻👍🏻

**Comment by riveign** [comment]
Thanks! Be sure to come to our [discord](https://discord.gg/fleekxyz) for news about the project!
