### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by roz2000** [fleekxyz/fleekxyz-support#12]
**Describe your feedback to the Fleek team.**
It was very easy to set up, it wasn't tiring at all and it wasn't confusing, congratulations to the team for making everything simple and clear, but we didn't enter our wallet or email anywhere while installing the node, I know it's not rewarded but it's a bit confusing as teams usually ask for these And is the image in the picture normal?
![ve](https://user-images.githubusercontent.com/113254415/217100344-7e7737cc-792a-4945-846d-f09b3ebd4be8.png)

**Comment by riveign** [comment]
Hi @roz2000 thanks for testing our services! I will be forwarding to the fleek network team this feedback! 

Unfortunately, this repository is about Fleek.xyz a platform for decentralized infrastructure! You are referring to Fleek Network in particular Ursa the CDN. This is the repository you can check to follow this discussion!

https://github.com/fleek-network/ursa

Also, there is some guides about the project so make sure you read them! https://docs.fleek.network/guides/Network%20nodes/fleek-network-managing-the-key-store
