### ISSUE TITLE
My feedback on using the Fleek Beta CLI

### ISSUE THREAD

**Issue by Mus156** [fleekxyz/fleekxyz-support#2]
First, I want to say thank you to the whole team for a great job!

I am not a developer yet, so my feedback will be closer to the average user. I have followed all the steps in the manual so far (https://docs.fleek.xyz).

I did IPFS pinning and IPNS mapping.

Everything was fast and successful. I did not encounter any problems.

I will attach a screenshot from the fleek ipns list command below.

Thanks again and I hope to keep the development going in the same nice spirit.
![111](https://user-images.githubusercontent.com/92182876/213531970-c1681aa8-24a4-4000-9013-a93b6d19c33d.png)

**Comment by riveign** [comment]
Hi, @Mus156 thanks for the feedback and for trying the product! Will share this with the team and stay tuned for future updates coming soon!
