### ISSUE TITLE
[Feedback]

### ISSUE THREAD

**Issue by vimihani** [fleekxyz/fleekxyz-support#3]
very easy to use, I have successfully tried Fleex CLI
i try create ifps https://ipfs.io/ipfs/QmQyPAPkJibyYNDzhi7TSLfgAJ1e3AeSRa5q1VXs8jZyQE/

**Comment by riveign** [comment]
@vimihani Thanks you very much for trying the product and giving your comments! Make sure to stay tuned for future updates in our [discord](https://discord.com/channels/965698989464887386/1024063350709170216) or [twitter](https://twitter.com/fleekxyz)
