### ISSUE TITLE
[BUG] Ability to run logout command when already logged out

### ISSUE THREAD

**Issue by alinasytnik** [fleekxyz/fleekxyz-support#5]
## Describe the bug
When a user has logged out and runs the logout command again, the "Success! Logged out" message appears.

## Precondition
The user must be logged out 

## To Reproduce
1. Type the `Login` command on the console > Press enter
2. On the App, press the Login button > Login with your email or Github
3. Press Confirm button
4. Type the logout command > Press enter
5. Type the logout command again
**Current:** The “Success! Logged out” message is showing up.

## Expected behavior
The “You are not logged in” message should be shown in CLI. 

## Screenshots
<img width="573" alt="Screenshot 2023-01-19 at 18 17 16" src="https://user-images.githubusercontent.com/33018206/213701460-b5487572-a352-4a0b-a246-0ddd3f8271f7.png">

## Desktop (please complete the following information):
 - OS: macOS Ventura 13.0.1
 - Browser: Chrome
 - Version: 0.0.1

**Comment by homoky** [comment]
Hey @alinasytnik. Thanks for reaching us. 

The logout command is doing the total clean up behind the scenes. You might have invalid token for example or other invalid data, so we are not checking if the credentials are valid or not. We are just cleaning everything so you want to be sure that no sensitive data like your token are stored on your computer. 

cc @riveign
