### ISSUE TITLE
[BUG] edit this page link on docs is broken

### ISSUE THREAD

**Issue by jcstein** [fleekxyz/fleekxyz-support#6]
**Describe the bug**
I originally meant to make an edit on https://docs.fleek.xyz/ to replace `Akask` with `Akash`, when I clicked "edit this page" there was a bug.

**To Reproduce**
1. Go to https://docs.fleek.xyz/
2. Click "edit this page" on the right bar
3. Results in page not found (probably an issue with config for "edit this page" in your docs site)
<img width="1162" alt="Screenshot 2023-01-20 at 1 18 37 PM" src="https://user-images.githubusercontent.com/46639943/213776694-42b7b7b1-0638-411f-82d4-ba0ecc98ac75.png">

**Expected behavior**
1. Able to edit page

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chromium (Arc/Brave), this is not browser-specific
 
**Additional context**

**Comment by riveign** [comment]
Hi! Nacho from the Fleek Team!

Thanks for the feedback we removed temporarily the edit link.
