### ISSUE TITLE
[BUG] process termination while waiting for authorisation

### ISSUE THREAD

**Issue by RomarioEXT** [fleekxyz/fleekxyz-support#7]
**Describe the bug**

During authorisation, the process terminates with an error without waiting for successful authorisation.

**To Reproduce**

- Type the **Login** command on the console
- **Current**: Change to waiting for authorisation on the web after "_Please login to continue_" output

**Expected behavior**
Waiting for authorisation on the web

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/109734150/214173602-3d44b030-e75d-4344-b150-78366d1e9700.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Version: 0.0.1

**Comment by riveign** [comment]
Hi @RomarioEXT, Nacho here from the Fleek team! Thanks for letting us know the feedback, we are looking it into with the team and will come back to you soon!

**Comment by RickyChez** [comment]
I got this error too. I think it has to do with the fact that we are running the client on a remote machine. When running on the localhost it works correctly.

**Comment by riveign** [comment]
Thanks for standing by! We have fixed this on version 0.1.1 available now on https://www.npmjs.com/package/@fleekxyz/cli
