### ISSUE TITLE
[BUG] crash when trying to login Error: spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by Renderlynx** [fleekxyz/fleekxyz-support#8]
**Describe the bug**

After the fleek login command, the application crashes

**To Reproduce**
1. Run "fleek login"
2. See error

**Expected behavior**

App waiting for authorisation.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/109742941/214704976-f3150487-326c-4e1f-8e3d-b0569bfda951.png)

**Desktop:**
- OS: Ubuntu 22.04
- NodeJS: 18.13.0
- Fleek: 0.0.2-rc.2

**Comment by riveign** [comment]
Hi @Renderlynx, Nacho here from the Fleek team! Thanks for letting us know the feedback, we are looking it into with the team and will come back to you soon!

**Comment by riveign** [comment]
Hi @Renderlynx Thanks for standing by! We have fixed this on version 0.1.1 available now on https://www.npmjs.com/package/@fleekxyz/cli
