### ISSUE TITLE
[BUG] - There should be an update of personal information to identify who is the operator of the node

### ISSUE THREAD

**Issue by Andytruong3978** [fleekxyz/fleekxyz-support#9]
I would like to have my node profile update entry on the node so that the project can identify who the node moderator is. For example, there is an item to update the wallet and private key so that when transferring the old VPS to the new VPS, I import it and do not lose the information that has been run from the old VPS.

**Comment by riveign** [comment]
Hi @Andytruong3978 it seems that you are referring to another project, Fleek Network. You can leave your request or questions regarding that project:

- In their repository: https://github.com/fleek-network/ursa
- Or in the community discord https://discord.gg/fleekxyz

Thanks for trying our products and leaving the feedback!

**Comment by heldrida** [comment]
@Andytruong3978 we provide documentation which addresses this topic, make sure you read https://docs.fleek.network/guides/Network%20nodes/fleek-network-managing-the-key-store
